server:
  port: 8081


logging:
  #log4j的配置文件地址
  config: /JAVA/git/fileServer/src/main/resources/log4j2-spring.xml
  level:
    com.ohh.fileServer.controller: trace
#连接Redis
spring:
  redis:
    #redis服务器地址
    host: 127.0.0.1
    #redis数据库索引
    database: 0
    #redis端口号
    port: 6379
    #redis密码
#    password: 0124
    #redis连接超时时间
    timeout: 1000
    jedis:
      pool:
        #redis连接池最大连接数（使用负数表示没有限制）
        max-active: 200
        #redis连接池最大组测等待时间（使用负数表示没有限制）
        max-wait: -1
        #redis连接池最大空闲连接
        max-idle: 10
        #redis连接池最小空闲连接
        min-idle: 0
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/fileServer?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: '0124'
    jackson:
      date-format: yyyy-MM-dd HH:mm:ss
      time-zone: GMT+8
      serialization:
        write-dates-as-timestamps: false

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    mapper-location: classpath*:mapper/**/*mapper.xml
    global-config:
      db-config:
        logic-delete-field: isDeleted
        logic-not-delete-value: 0
        logic-delete-value: 1
